title: Zach Santangelo (SDE)
tagline: Professional and Hobbyist Programmer
tags: 
  - Software Developer
  - Software Engineer
  - Software Development Engineer
theme: jekyll-theme-hacker
baseurl: /Qazzzie
source: /Qazzzie
